name: Compile Examples
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:samd:mkrzero

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}